"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.DEFAULT_PROPERTIES = exports.BLOCK = exports.CLICK = exports.SPACE = exports.EMPTY_STRING = exports.BODY = exports.UNDEFINED = exports.MOUSEOUT = exports.DISPLAY = exports.OBJECT = exports.LEFT_MOUSE_BUTTON = exports.CLASS_NAME = exports.RIGHT_MOUSE_BUTTON = exports.TEXT_HTML = exports.CLASS = exports.WIDTH = exports.MIDDLE_MOUSE_BUTTON = exports.WILDCARD = exports.DISABLED = exports.HTML_FOR = exports.ABOUT_BLANK = exports.FUNCTION = exports.HEIGHT = exports.SVG_NAMESPACE_URI = exports.CHANGE = exports.KEYDOWN = exports.default = exports.KEYUP = exports.NONE = exports.MOUSEMOVE = exports.MOUSEDOWN = exports.MOUSEUP = exports.STRING = exports.RESIZE = exports.SCROLL = exports.FOR = exports.MOUSEOVER = exports.BOOLEAN = exports.IGNORED_PROPERTIES = void 0;
var FOR = "for";
exports.FOR = FOR;
var BODY = "body";
exports.BODY = BODY;
var NONE = "none";
exports.NONE = NONE;
var SPACE = " ";
exports.SPACE = SPACE;
var CLASS = "class";
exports.CLASS = CLASS;
var CLICK = "click";
exports.CLICK = CLICK;
var KEYUP = "keyup";
exports.KEYUP = KEYUP;
var WIDTH = "width";
exports.WIDTH = WIDTH;
var BLOCK = "block";
exports.BLOCK = BLOCK;
var HEIGHT = "height";
exports.HEIGHT = HEIGHT;
var OBJECT = "object";
exports.OBJECT = OBJECT;
var CHANGE = "change";
exports.CHANGE = CHANGE;
var RESIZE = "resize";
exports.RESIZE = RESIZE;
var SCROLL = "scroll";
exports.SCROLL = SCROLL;
var STRING = "string";
exports.STRING = STRING;
var DISPLAY = "display";
exports.DISPLAY = DISPLAY;
var KEYDOWN = "keydown";
exports.KEYDOWN = KEYDOWN;
var BOOLEAN = "boolean";
exports.BOOLEAN = BOOLEAN;
var MOUSEUP = "mouseup";
exports.MOUSEUP = MOUSEUP;
var DISABLED = "disabled";
exports.DISABLED = DISABLED;
var FUNCTION = "function";
exports.FUNCTION = FUNCTION;
var WILDCARD = "*";
exports.WILDCARD = WILDCARD;
var MOUSEOUT = "mouseout";
exports.MOUSEOUT = MOUSEOUT;
var HTML_FOR = "htmlFor";
exports.HTML_FOR = HTML_FOR;
var UNDEFINED = 'undefined';
exports.UNDEFINED = UNDEFINED;
var MOUSEOVER = "mouseover";
exports.MOUSEOVER = MOUSEOVER;
var MOUSEDOWN = "mousedown";
exports.MOUSEDOWN = MOUSEDOWN;
var MOUSEMOVE = "mousemove";
exports.MOUSEMOVE = MOUSEMOVE;
var TEXT_HTML = "text/html";
exports.TEXT_HTML = TEXT_HTML;
var CLASS_NAME = "className";
exports.CLASS_NAME = CLASS_NAME;
var ABOUT_BLANK = "about:blank";
exports.ABOUT_BLANK = ABOUT_BLANK;
var EMPTY_STRING = "";
exports.EMPTY_STRING = EMPTY_STRING;
var SVG_NAMESPACE_URI = "http://www.w3.org/2000/svg";
exports.SVG_NAMESPACE_URI = SVG_NAMESPACE_URI;
var DEFAULT_PROPERTIES = "defaultProperties";
exports.DEFAULT_PROPERTIES = DEFAULT_PROPERTIES;
var IGNORED_PROPERTIES = "ignoredProperties";
exports.IGNORED_PROPERTIES = IGNORED_PROPERTIES;
var LEFT_MOUSE_BUTTON = 0;
exports.LEFT_MOUSE_BUTTON = LEFT_MOUSE_BUTTON;
var RIGHT_MOUSE_BUTTON = 2;
exports.RIGHT_MOUSE_BUTTON = RIGHT_MOUSE_BUTTON;
var MIDDLE_MOUSE_BUTTON = 1;
exports.MIDDLE_MOUSE_BUTTON = MIDDLE_MOUSE_BUTTON;
var _default = {
    LEFT_MOUSE_BUTTON: LEFT_MOUSE_BUTTON,
    RIGHT_MOUSE_BUTTON: RIGHT_MOUSE_BUTTON,
    MIDDLE_MOUSE_BUTTON: MIDDLE_MOUSE_BUTTON
};
exports.default = _default;
