"use strict";

export const FOR = "for";
export const BODY = "body";
export const NONE = "none";
export const SPACE = " ";
export const CLASS = "class";
export const WIDTH = "width";
export const BLOCK = "block";
export const HEIGHT = "height";
export const OBJECT = "object";
export const STRING = "string";
export const DISPLAY = "display";
export const BOOLEAN = "boolean";
export const DISABLED = "disabled";
export const FUNCTION = "function";
export const WILDCARD = "*";
export const HTML_FOR = "htmlFor";
export const UNDEFINED = 'undefined';
export const CLASS_NAME = "className";
export const EMPTY_STRING = "";
export const SVG_NAMESPACE_URI = "http://www.w3.org/2000/svg";
export const DEFAULT_PROPERTIES = "defaultProperties";
export const IGNORED_PROPERTIES = "ignoredProperties";
